# If the plugin should auto-update
auto-update: true
on-death:
  # If true, a player will lose a random research every death
  reset-random-research: true
  # Chance to reset all the player's researches on death. Percent scale of 0 to 100.
  # 100 will always fire and 0 will never fire.
  chance-to-reset-all-researches: 5

on-research:
  # Chance that researching can fail. Percent scale of 0 to 100.
  # 100 will always fire and 0 will never fire.
  chance-of-failure: 10

android:
  # Chance for the Android to malfunction. Percent scale of 0 to 100.
  # 100 will always fire and 0 will never fire.
  chance-to-malfunction: 10
  # Duration of the malfunction in seconds.
  malfunction-duration: 30

messages:
  # %research% can be used to show the lost research's name
  lost-random-research: '&cYou lost a random research!'
  lost-all-research: '&cOh noes... You lost all your research!'
  research-failed: '&cResearch failed! You''ll need to do that again :^)'
  android-malfunctioned: '&cYour Android has malfunctioned! Let it cool down and start it again'
